Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Wed Nov 15 18:17:34 GMT 2023
/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/dask/config.py:742: FutureWarning: Dask configuration key 'distributed.scheduler.transition-log-length' has been deprecated; please use 'distributed.admin.low-level-log-length' instead
  warnings.warn(
/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/dask/config.py:742: FutureWarning: Dask configuration key 'distributed.comm.recent-messages-log-length' has been deprecated; please use 'distributed.admin.low-level-log-length' instead
  warnings.warn(
Number of workers up = 0
Number of workers up = 0
Number of workers up = 0
Number of workers up = 0
Number of workers up = 0
Number of workers up = 0
Number of workers up = 0
Number of workers up = 0
Number of workers up = 0
Number of workers up = 0
Number of workers up = 0
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 40
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 60
Number of workers up = 100
Number of workers up = 100
Number of workers up = 140
Number of workers up = 140
Number of workers up = 140
Number of workers up = 140
Number of workers up = 160
Number of workers up = 180
Cluster is up, proceeding with computations
Traceback (most recent call last):
  File "/home1/datahome/mdemol/historical_analysis/job_distributed.py", line 307, in <module>
    if dataset == 'eras' : run_eras(l, cluster, client)
  File "/home1/datahome/mdemol/historical_analysis/job_distributed.py", line 259, in run_eras
    ds_es = eras.compute_eras(ds_data, dt=(-12,13), only_matchup_time = True).chunk({'obs':200, 'alti_time':-1, 'site_obs':-1}).persist()
  File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/xarray/core/dataset.py", line 2184, in chunk
    raise ValueError(
ValueError: some chunks keys are not dimensions on this object: {'alti_time'}
Wed Nov 15 18:32:48 GMT 2023
