Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Thu Nov  2 15:30:00 GMT 2023
/home1/datahome/mdemol/historical_analysis/launch/jlab.py:29: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif dashinfo is not "0":
/home1/datahome/mdemol/historical_analysis/launch/jlab.py:32: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if dashinfo is not "0":
[I 2023-11-02 15:30:01.020 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-11-02 15:30:01.042 ServerApp] Package jupyter_lsp took 0.0214s to import
[W 2023-11-02 15:30:01.042 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-02 15:30:01.050 ServerApp] Package jupyter_server_terminals took 0.0083s to import
[I 2023-11-02 15:30:01.051 ServerApp] Package notebook took 0.0000s to import
[I 2023-11-02 15:30:01.053 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-11-02 15:30:01.053 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-02 15:30:02.587 ServerApp] Package panel.io.jupyter_server_extension took 1.5333s to import
[I 2023-11-02 15:30:02.588 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-11-02 15:30:02.592 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-11-02 15:30:02.597 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-11-02 15:30:02.599 JupyterNotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-11-02 15:30:02.603 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2023-11-02 15:30:02.603 ServerApp] notebook | extension was successfully linked.
[I 2023-11-02 15:30:02.943 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-11-02 15:30:02.944 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2023-11-02 15:30:02.980 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-11-02 15:30:02.983 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-11-02 15:30:02.984 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-11-02 15:30:02.988 LabApp] JupyterLab extension loaded from /home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyterlab
[I 2023-11-02 15:30:02.988 LabApp] JupyterLab application directory is /home1/datahome/mdemol/.miniconda3/envs/histenv2/share/jupyter/lab
[I 2023-11-02 15:30:02.988 LabApp] Extension Manager is 'pypi'.
[I 2023-11-02 15:30:02.991 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-11-02 15:30:02.995 ServerApp] notebook | extension was successfully loaded.
[I 2023-11-02 15:30:02.996 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2023-11-02 15:30:02.996 ServerApp] Serving notebooks from local directory: /home1/datahome/mdemol
[I 2023-11-02 15:30:02.996 ServerApp] Jupyter Server 2.9.1 is running at:
[I 2023-11-02 15:30:02.996 ServerApp] http://r2i0n25:8877/lab
[I 2023-11-02 15:30:02.996 ServerApp]     http://127.0.0.1:8877/lab
[I 2023-11-02 15:30:02.996 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2023-11-02 15:30:03.033 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-11-02 15:30:04.676 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8?1698939004546 (10.148.1.145): Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[W 2023-11-02 15:30:04.676 ServerApp] wrote error: 'Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8)
[W 2023-11-02 15:30:04.678 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8?1698939004546 (561c211cf284414792903f89972ed90c@10.148.1.145) 3.04ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-02 15:30:05.275 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8/channels?session_id=f25f2ea3-7d9d-454f-b472-a4c644125138 (10.148.1.145): Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[W 2023-11-02 15:30:05.301 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8/channels?session_id=f25f2ea3-7d9d-454f-b472-a4c644125138 (561c211cf284414792903f89972ed90c@10.148.1.145) 26.21ms referer=None
[W 2023-11-02 15:30:05.369 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8?1698939005290 (10.148.1.145): Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[W 2023-11-02 15:30:05.369 ServerApp] wrote error: 'Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8)
[W 2023-11-02 15:30:05.370 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8?1698939005290 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.11ms referer=http://localhost:8877/lab/tree/m2_2022/sandbox/zarr_coloc.ipynb
[W 2023-11-02 15:30:06.763 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8/channels?session_id=f25f2ea3-7d9d-454f-b472-a4c644125138 (10.148.1.145): Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[W 2023-11-02 15:30:06.763 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8/channels?session_id=f25f2ea3-7d9d-454f-b472-a4c644125138 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.02ms referer=None
[W 2023-11-02 15:30:06.821 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8?1698939006741 (10.148.1.145): Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[W 2023-11-02 15:30:06.821 ServerApp] wrote error: 'Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8)
[W 2023-11-02 15:30:06.821 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8?1698939006741 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.87ms referer=http://localhost:8877/lab/tree/m2_2022/sandbox/zarr_coloc.ipynb
[W 2023-11-02 15:30:07.609 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8/channels?session_id=f25f2ea3-7d9d-454f-b472-a4c644125138 (10.148.1.145): Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[W 2023-11-02 15:30:07.610 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8/channels?session_id=f25f2ea3-7d9d-454f-b472-a4c644125138 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.00ms referer=None
[W 2023-11-02 15:30:07.757 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8?1698939007674 (10.148.1.145): Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8
[W 2023-11-02 15:30:07.757 ServerApp] wrote error: 'Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: a56a2820-8511-4d66-88d5-d635d3cfa5c8)
[W 2023-11-02 15:30:07.758 ServerApp] 404 GET /api/kernels/a56a2820-8511-4d66-88d5-d635d3cfa5c8?1698939007674 (561c211cf284414792903f89972ed90c@10.148.1.145) 0.87ms referer=http://localhost:8877/lab/tree/m2_2022/sandbox/zarr_coloc.ipynb
[I 2023-11-02 15:30:24.607 ServerApp] Kernel started: f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:30:25.236 ServerApp] Connecting to kernel f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a.
[I 2023-11-02 15:31:18.531 ServerApp] Kernel started: f9a0b833-3c08-4654-9865-9250823e1ed8
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:31:20.487 ServerApp] Connecting to kernel f9a0b833-3c08-4654-9865-9250823e1ed8.
[I 2023-11-02 15:31:45.871 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:32:25.711 ServerApp] Saving file at /m2_2022/sandbox/zarr_matchup.ipynb
[W 2023-11-02 15:32:25.917 ServerApp] /home1/datahome/mdemol/m2_2022/sandbox/.~zarr_matchup.ipynb doesn't exist
[I 2023-11-02 15:33:20.879 ServerApp] Saving file at /m2_2022/sandbox/zarr_stat_lonlat.ipynb
[I 2023-11-02 15:34:03.323 ServerApp] Kernel started: 883e4197-5bdf-49ee-9ba6-a09969075ccd
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:34:06.731 ServerApp] Connecting to kernel 883e4197-5bdf-49ee-9ba6-a09969075ccd.
[I 2023-11-02 15:34:50.348 ServerApp] Starting buffering for f9a0b833-3c08-4654-9865-9250823e1ed8:c060e9cb-f8a6-4740-b890-d5583a174e84
[I 2023-11-02 15:36:01.424 ServerApp] Saving file at /m2_2022/sandbox/zarr_wind.ipynb
[I 2023-11-02 15:36:08.919 ServerApp] Kernel started: 54d7b563-d536-47a4-aaa2-26ce93745185
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:36:09.838 ServerApp] Connecting to kernel 54d7b563-d536-47a4-aaa2-26ce93745185.
[I 2023-11-02 15:37:42.519 ServerApp] Kernel started: be5b2e84-e5c5-411d-9ef2-be0ead5215d1
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:37:43.406 ServerApp] Connecting to kernel be5b2e84-e5c5-411d-9ef2-be0ead5215d1.
[I 2023-11-02 15:37:47.382 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:37:54.124 ServerApp] Starting buffering for f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a:9b479967-b5c9-4ab8-8b55-e4914c9f957a
[I 2023-11-02 15:37:54.125 ServerApp] Starting buffering for be5b2e84-e5c5-411d-9ef2-be0ead5215d1:59dc3e79-5320-4b8b-831e-2bf9335d4ccb
[I 2023-11-02 15:37:54.125 ServerApp] Starting buffering for 54d7b563-d536-47a4-aaa2-26ce93745185:bc41d7b3-f5a1-4691-bc96-db4dc28f9894
[I 2023-11-02 15:37:54.125 ServerApp] Starting buffering for 883e4197-5bdf-49ee-9ba6-a09969075ccd:f3de146a-eee1-40e2-aae9-5a31a4a01b84
[I 2023-11-02 15:38:08.746 ServerApp] Connecting to kernel f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a.
[I 2023-11-02 15:38:08.746 ServerApp] Restoring connection for f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a:9b479967-b5c9-4ab8-8b55-e4914c9f957a
[I 2023-11-02 15:38:09.182 ServerApp] Connecting to kernel 883e4197-5bdf-49ee-9ba6-a09969075ccd.
[I 2023-11-02 15:38:09.183 ServerApp] Restoring connection for 883e4197-5bdf-49ee-9ba6-a09969075ccd:f3de146a-eee1-40e2-aae9-5a31a4a01b84
[I 2023-11-02 15:38:10.853 ServerApp] Saving file at /m2_2022/sandbox/zarr_slacorrection.ipynb
[I 2023-11-02 15:38:16.831 ServerApp] Connecting to kernel be5b2e84-e5c5-411d-9ef2-be0ead5215d1.
[I 2023-11-02 15:38:16.831 ServerApp] Restoring connection for be5b2e84-e5c5-411d-9ef2-be0ead5215d1:59dc3e79-5320-4b8b-831e-2bf9335d4ccb
[I 2023-11-02 15:38:17.855 ServerApp] Connecting to kernel 54d7b563-d536-47a4-aaa2-26ce93745185.
[I 2023-11-02 15:38:17.855 ServerApp] Restoring connection for 54d7b563-d536-47a4-aaa2-26ce93745185:bc41d7b3-f5a1-4691-bc96-db4dc28f9894
[I 2023-11-02 15:38:37.336 ServerApp] Starting buffering for 883e4197-5bdf-49ee-9ba6-a09969075ccd:f3de146a-eee1-40e2-aae9-5a31a4a01b84
[I 2023-11-02 15:38:37.339 ServerApp] Starting buffering for f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a:9b479967-b5c9-4ab8-8b55-e4914c9f957a
[I 2023-11-02 15:38:37.339 ServerApp] Starting buffering for be5b2e84-e5c5-411d-9ef2-be0ead5215d1:59dc3e79-5320-4b8b-831e-2bf9335d4ccb
[I 2023-11-02 15:38:37.339 ServerApp] Starting buffering for 54d7b563-d536-47a4-aaa2-26ce93745185:bc41d7b3-f5a1-4691-bc96-db4dc28f9894
[W 2023-11-02 15:38:39.015 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-02 15:38:39.159 ServerApp] Connecting to kernel f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a.
[I 2023-11-02 15:38:39.165 ServerApp] Connecting to kernel f9a0b833-3c08-4654-9865-9250823e1ed8.
[I 2023-11-02 15:38:39.168 ServerApp] Connecting to kernel 883e4197-5bdf-49ee-9ba6-a09969075ccd.
[I 2023-11-02 15:38:39.173 ServerApp] Connecting to kernel 54d7b563-d536-47a4-aaa2-26ce93745185.
[I 2023-11-02 15:38:39.176 ServerApp] Connecting to kernel be5b2e84-e5c5-411d-9ef2-be0ead5215d1.
[I 2023-11-02 15:38:39.298 ServerApp] Starting buffering for f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a:434f18ed-5823-4320-8f4e-1a4ecc155975
[I 2023-11-02 15:38:39.342 ServerApp] Starting buffering for f9a0b833-3c08-4654-9865-9250823e1ed8:5cdc5105-5ada-428e-9853-2b900efa2cf2
[I 2023-11-02 15:38:39.347 ServerApp] Starting buffering for 883e4197-5bdf-49ee-9ba6-a09969075ccd:e27148e4-3157-4912-bdfc-a099e82a15a5
[I 2023-11-02 15:38:39.349 ServerApp] Starting buffering for 54d7b563-d536-47a4-aaa2-26ce93745185:c37670fd-dd18-4d80-a034-941903bc0ca7
[I 2023-11-02 15:38:39.368 ServerApp] Starting buffering for be5b2e84-e5c5-411d-9ef2-be0ead5215d1:eccddc55-8aaa-4cec-ba87-8890b851dd8b
[I 2023-11-02 15:38:47.568 ServerApp] Connecting to kernel 883e4197-5bdf-49ee-9ba6-a09969075ccd.
[I 2023-11-02 15:38:47.913 ServerApp] Kernel started: 32e2c6bb-9b1e-46ae-84d3-ab31319c56ff
[I 2023-11-02 15:38:47.919 ServerApp] Connecting to kernel 54d7b563-d536-47a4-aaa2-26ce93745185.
[I 2023-11-02 15:38:47.928 ServerApp] Connecting to kernel be5b2e84-e5c5-411d-9ef2-be0ead5215d1.
readline: /etc/inputrc: line 19: term: unknown variable name
[I 2023-11-02 15:38:49.179 ServerApp] Connecting to kernel f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a.
[I 2023-11-02 15:38:49.184 ServerApp] Connecting to kernel 32e2c6bb-9b1e-46ae-84d3-ab31319c56ff.
[I 2023-11-02 15:40:48.072 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:42:49.208 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[I 2023-11-02 15:46:50.537 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[C 2023-11-02 15:47:42.984 ServerApp] received signal 15, stopping
Terminated
[I 2023-11-02 15:47:43.036 ServerApp] Shutting down 6 extensions
[I 2023-11-02 15:47:43.036 ServerApp] Shutting down 6 kernels
[I 2023-11-02 15:47:43.036 ServerApp] Kernel shutdown: 54d7b563-d536-47a4-aaa2-26ce93745185
[I 2023-11-02 15:47:43.037 ServerApp] Kernel shutdown: f9a0b833-3c08-4654-9865-9250823e1ed8
[I 2023-11-02 15:47:43.037 ServerApp] Kernel shutdown: be5b2e84-e5c5-411d-9ef2-be0ead5215d1
[I 2023-11-02 15:47:43.037 ServerApp] Kernel shutdown: f3f17908-28f5-4a3a-8a8c-94fa9fd02b1a
[I 2023-11-02 15:47:43.037 ServerApp] Kernel shutdown: 32e2c6bb-9b1e-46ae-84d3-ab31319c56ff
[I 2023-11-02 15:47:43.037 ServerApp] Kernel shutdown: 883e4197-5bdf-49ee-9ba6-a09969075ccd
