Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Fri Nov  3 08:07:28 GMT 2023
/home1/datahome/mdemol/historical_analysis/launch/jlab.py:29: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif dashinfo is not "0":
/home1/datahome/mdemol/historical_analysis/launch/jlab.py:32: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if dashinfo is not "0":
[I 2023-11-03 08:07:48.648 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-11-03 08:07:49.111 ServerApp] Package jupyter_lsp took 0.4620s to import
[W 2023-11-03 08:07:49.111 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-03 08:07:49.402 ServerApp] Package jupyter_server_terminals took 0.2908s to import
[I 2023-11-03 08:07:49.402 ServerApp] Package notebook took 0.0000s to import
[I 2023-11-03 08:07:49.405 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-11-03 08:07:49.405 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-03 08:08:11.972 ServerApp] Package panel.io.jupyter_server_extension took 22.5531s to import
[I 2023-11-03 08:08:11.972 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-11-03 08:08:11.978 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-11-03 08:08:11.984 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-11-03 08:08:11.991 JupyterNotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-11-03 08:08:11.994 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2023-11-03 08:08:11.994 ServerApp] notebook | extension was successfully linked.
[I 2023-11-03 08:08:17.483 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-11-03 08:08:17.483 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2023-11-03 08:08:17.790 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-11-03 08:08:17.792 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-11-03 08:08:17.794 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-11-03 08:08:17.926 LabApp] JupyterLab extension loaded from /home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyterlab
[I 2023-11-03 08:08:17.926 LabApp] JupyterLab application directory is /home1/datahome/mdemol/.miniconda3/envs/histenv2/share/jupyter/lab
[I 2023-11-03 08:08:17.935 LabApp] Extension Manager is 'pypi'.
[I 2023-11-03 08:08:17.938 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-11-03 08:08:17.942 ServerApp] notebook | extension was successfully loaded.
[I 2023-11-03 08:08:17.943 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2023-11-03 08:08:17.943 ServerApp] Serving notebooks from local directory: /home1/datahome/mdemol
[I 2023-11-03 08:08:17.943 ServerApp] Jupyter Server 2.9.1 is running at:
[I 2023-11-03 08:08:17.943 ServerApp] http://r2i0n21:8877/lab
[I 2023-11-03 08:08:17.943 ServerApp]     http://127.0.0.1:8877/lab
[I 2023-11-03 08:08:17.943 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2023-11-03 08:08:18.087 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-11-03 08:23:15.514 ServerApp] 404 GET /api/kernels/1dccfb73-51c4-4dc5-b866-7b61f161e120?1698999795455 (10.148.1.145): Kernel does not exist: 1dccfb73-51c4-4dc5-b866-7b61f161e120
[W 2023-11-03 08:23:15.515 ServerApp] wrote error: 'Kernel does not exist: 1dccfb73-51c4-4dc5-b866-7b61f161e120'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 1dccfb73-51c4-4dc5-b866-7b61f161e120)
[W 2023-11-03 08:23:15.551 ServerApp] 404 GET /api/kernels/1dccfb73-51c4-4dc5-b866-7b61f161e120?1698999795455 (561c211cf284414792903f89972ed90c@10.148.1.145) 37.70ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-03 08:23:15.866 ServerApp] 404 GET /api/kernels/1dccfb73-51c4-4dc5-b866-7b61f161e120/channels?session_id=eb84266f-029a-4865-a7ff-b4c44aabd24f (10.148.1.145): Kernel does not exist: 1dccfb73-51c4-4dc5-b866-7b61f161e120
[W 2023-11-03 08:23:16.004 ServerApp] 404 GET /api/kernels/1dccfb73-51c4-4dc5-b866-7b61f161e120/channels?session_id=eb84266f-029a-4865-a7ff-b4c44aabd24f (561c211cf284414792903f89972ed90c@10.148.1.145) 138.44ms referer=None
[W 2023-11-03 08:23:16.112 ServerApp] 404 GET /api/kernels/1dccfb73-51c4-4dc5-b866-7b61f161e120?1698999796016 (10.148.1.145): Kernel does not exist: 1dccfb73-51c4-4dc5-b866-7b61f161e120
[W 2023-11-03 08:23:16.112 ServerApp] wrote error: 'Kernel does not exist: 1dccfb73-51c4-4dc5-b866-7b61f161e120'
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 1dccfb73-51c4-4dc5-b866-7b61f161e120)
[W 2023-11-03 08:23:16.113 ServerApp] 404 GET /api/kernels/1dccfb73-51c4-4dc5-b866-7b61f161e120?1698999796016 (561c211cf284414792903f89972ed90c@10.148.1.145) 1.10ms referer=http://localhost:8877/lab/tree/historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-03 08:23:28.643 ServerApp] delete /GDP_analysis
[I 2023-11-03 08:23:54.289 ServerApp] Saving file at /historical_analysis/1_zarr_coloc.ipynb
[W 2023-11-03 08:24:29.678 ServerApp] delete /historical_analysis/sandbox
[W 2023-11-03 08:24:36.242 ServerApp] delete /historical_analysis/m2_2022.egg-info
[W 2023-11-03 08:24:58.488 ServerApp] delete /tmp.py
[W 2023-11-03 08:25:07.864 ServerApp] delete /drifters_stats
[W 2023-11-03 08:37:04.174 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-11-03 08:37:16.150 ServerApp] Kernel started: 548d8954-0a36-49d6-bec8-d4e3f76ff2c9
[I 2023-11-03 08:37:16.152 ServerApp] Kernel started: 62743b22-d57b-4c3b-810a-f7d261239678
Exception in thread Heartbeat:
Traceback (most recent call last):
  File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/ipykernel/heartbeat.py", line 99, in run
    self._bind_socket()
  File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/ipykernel/heartbeat.py", line 78, in _bind_socket
    self._try_bind_socket()
  File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/ipykernel/heartbeat.py", line 65, in _try_bind_socket
    return self.socket.bind(f"{self.transport}://{self.ip}" + c + str(self.port))
  File "/home1/datahome/mdemol/.miniconda3/envs/histenv2/lib/python3.9/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:54499')
readline: readline: /etc/inputrc: line 19: term: unknown variable name
/etc/inputrc: line 19: term: unknown variable name
[I 2023-11-03 08:37:46.299 ServerApp] Connecting to kernel 62743b22-d57b-4c3b-810a-f7d261239678.
[I 2023-11-03 08:37:46.301 ServerApp] Connecting to kernel 62743b22-d57b-4c3b-810a-f7d261239678.
[I 2023-11-03 08:37:46.302 ServerApp] Connecting to kernel 62743b22-d57b-4c3b-810a-f7d261239678.
[I 2023-11-03 08:37:46.339 ServerApp] Connecting to kernel 548d8954-0a36-49d6-bec8-d4e3f76ff2c9.
[C 2023-11-03 09:11:42.591 ServerApp] received signal 15, stopping
Terminated
[I 2023-11-03 09:11:42.593 ServerApp] Shutting down 6 extensions
[I 2023-11-03 09:11:42.594 ServerApp] Shutting down 2 kernels
[I 2023-11-03 09:11:42.594 ServerApp] Kernel shutdown: 548d8954-0a36-49d6-bec8-d4e3f76ff2c9
[I 2023-11-03 09:11:42.594 ServerApp] Kernel shutdown: 62743b22-d57b-4c3b-810a-f7d261239678
